export const CREATE_EMPRENDIMIENTO_REQUEST = "CREATE_EMPRENDIMIENTO_REQUEST";
export const CREATE_EMPRENDIMIENTO_SUCCESS = "CREATE_EMPRENDIMIENTO_SUCCESS";
export const CREATE_EMPRENDIMIENTO_FAILURE = "CREATE_EMPRENDIMIENTO_FAILURE";

export const RETRIEVE_EMPRENDIMIENTOS_REQUEST = "RETRIEVE_EMPRENDIMIENTOS_REQUEST";
export const RETRIEVE_EMPRENDIMIENTOS_SUCCESS = "RETRIEVE_EMPRENDIMIENTOS_SUCCESS";
export const RETRIEVE_EMPRENDIMIENTOS_FAILURE = "RETRIEVE_EMPRENDIMIENTOS_FAILURE";

export const UPDATE_EMPRENDIMIENTO_REQUEST = "UPDATE_EMPRENDIMIENTO_REQUEST";
export const UPDATE_EMPRENDIMIENTO_SUCCESS = "UPDATE_EMPRENDIMIENTO_SUCCESS";
export const UPDATE_EMPRENDIMIENTO_FAILURE = "UPDATE_EMPRENDIMIENTO_FAILURE";

export const DELETE_EMPRENDIMIENTO_REQUEST = "DELETE_EMPRENDIMIENTO_REQUEST";
export const DELETE_EMPRENDIMIENTO_SUCCESS = "DELETE_EMPRENDIMIENTO_SUCCESS";
export const DELETE_EMPRENDIMIENTO_FAILURE = "DELETE_EMPRENDIMIENTO_FAILURE";

export const GET_EMPRENDIMIENTO_BY_ID_REQUEST = "GET_EMPRENDIMIENTO_BY_ID_REQUEST";
export const GET_EMPRENDIMIENTO_BY_ID_SUCCESS = "GET_EMPRENDIMIENTO_BY_ID_SUCCESS";
export const GET_EMPRENDIMIENTO_BY_ID_FAILURE = "GET_EMPRENDIMIENTO_BY_ID_FAILURE";

export const DELETE_ALL_EMPRENDIMIENTOS = "DELETE_ALL_EMPRENDIMIENTOS";