export const CREATE_EMPRENDEDOR_REQUEST = "CREATE_EMPRENDEDOR_REQUEST";
export const CREATE_EMPRENDEDOR_SUCCESS = "CREATE_EMPRENDEDOR_SUCCESS";
export const CREATE_EMPRENDEDOR_FAILURE = "CREATE_EMPRENDEDOR_FAILURE";

export const RETRIEVE_EMPRENDEDOR_REQUEST = "RETRIEVE_EMPRENDEDOR_REQUEST";
export const RETRIEVE_EMPRENDEDOR_SUCCESS = "RETRIEVE_EMPRENDEDOR_SUCCESS";
export const RETRIEVE_EMPRENDEDOR_FAILURE = "RETRIEVE_EMPRENDEDOR_FAILURE";

export const UPDATE_EMPRENDEDOR_REQUEST = "UPDATE_EMPRENDEDOR_REQUEST";
export const UPDATE_EMPRENDEDOR_SUCCESS = "UPDATE_EMPRENDEDOR_SUCCESS";
export const UPDATE_EMPRENDEDOR_FAILURE = "UPDATE_EMPRENDEDOR_FAILURE";

export const DELETE_EMPRENDEDOR_REQUEST = "DELETE_EMPRENDEDOR_REQUEST";
export const DELETE_EMPRENDEDOR_SUCCESS = "DELETE_EMPRENDEDOR_SUCCESS";
export const DELETE_EMPRENDEDOR_FAILURE = "DELETE_EMPRENDEDOR_FAILURE";

export const GET_EMPRENDEDOR_BY_ID_REQUEST = "GET_EMPRENDEDOR_BY_ID_REQUEST";
export const GET_EMPRENDEDOR_BY_ID_SUCCESS = "GET_EMPRENDEDOR_BY_ID_SUCCESS";
export const GET_EMPRENDEDOR_BY_ID_FAILURE = "GET_EMPRENDEDOR_BY_ID_FAILURE";

export const DELETE_ALL_EMPRENDEDEDORES = "DELETE_ALL_EMPRENDEDORES";