export const CREATE_INSCRIPCION_REQUEST = "CREATE_INSCRIPCION_REQUEST";
export const CREATE_INSCRIPCION_SUCCESS = "CREATE_INSCRIPCION_SUCCESS";
export const CREATE_INSCRIPCION_FAILURE = "CREATE_INSCRIPCION_FAILURE";

export const RETRIEVE_INSCRIPCIONES_REQUEST = "RETRIEVE_INSCRIPCION_REQUEST";
export const RETRIEVE_INSCRIPCIONES_SUCCESS = "RETRIEVE_INSCRIPCION_SUCCESS";
export const RETRIEVE_INSCRIPCIONES_FAILURE = "RETRIEVE_INSCRIPCION_FAILURE";

export const UPDATE_INSCRIPCION_REQUEST = "UPDATE_INSCRIPCION_REQUEST";
export const UPDATE_INSCRIPCION_SUCCESS = "UPDATE_INSCRIPCION_SUCCESS";
export const UPDATE_INSCRIPCION_FAILURE = "UPDATE_INSCRIPCION_FAILURE";

export const DELETE_INSCRIPCION_REQUEST = "DELETE_INSCRIPCION_REQUEST";
export const DELETE_INSCRIPCION_SUCCESS = "DELETE_INSCRIPCION_SUCCESS";
export const DELETE_INSCRIPCION_FAILURE = "DELETE_INSCRIPCION_FAILURE";

export const GET_INSCRIPCION_BY_ID_REQUEST = "GET_INSCRIPCION_BY_ID_REQUEST";
export const GET_INSCRIPCION_BY_ID_SUCCESS = "GET_INSCRIPCION_BY_ID_SUCCESS";
export const GET_INSCRIPCION_BY_ID_FAILURE = "GET_INSCRIPCION_BY_ID_FAILURE";

export const DELETE_ALL_INSCRIPCIONES = "DELETE_ALL_INSCRIPCIONES";