export const CREATE_PROCESO_REQUEST = "CREATE_PROCESO_REQUEST";
export const CREATE_PROCESO_SUCCESS = "CREATE_PROCESO_SUCCESS";
export const CREATE_PROCESO_FAILURE = "CREATE_PROCESO_FAILURE";

export const RETRIEVE_PROCESO_REQUEST = "RETRIEVE_PROCESO_REQUEST";
export const RETRIEVE_PROCESO_SUCCESS = "RETRIEVE_PROCESO_SUCCESS";
export const RETRIEVE_PROCESO_FAILURE = "RETRIEVE_PROCESO_FAILURE";

export const UPDATE_PROCESO_REQUEST = "UPDATE_PROCESO_REQUEST";
export const UPDATE_PROCESO_SUCCESS = "UPDATE_PROCESO_SUCCESS";
export const UPDATE_PROCESO_FAILURE = "UPDATE_PROCESO_FAILURE";

export const DELETE_PROCESO_REQUEST = "DELETE_PROCESO_REQUEST";
export const DELETE_PROCESO_SUCCESS = "DELETE_PROCESO_SUCCESS";
export const DELETE_PROCESO_FAILURE = "DELETE_PROCESO_FAILURE";

export const GET_PROCESO_BY_ID_REQUEST = "GET_PROCESO_BY_ID_REQUEST";
export const GET_PROCESO_BY_ID_SUCCESS = "GET_PROCESO_BY_ID_SUCCESS";
export const GET_PROCESO_BY_ID_FAILURE = "GET_PROCESO_BY_ID_FAILURE";

export const DELETE_ALL_PROCESO = "DELETE_ALL_PROCESO";