export const CREATE_NOVEDAD_REQUEST = "CREATE_NOVEDADES_REQUEST";
export const CREATE_NOVEDAD_SUCCESS = "CREATE_NOVEDADES_SUCCESS";
export const CREATE_NOVEDAD_FAILURE = "CREATE_NOVEDADES_FAILURE";

export const RETRIEVE_NOVEDADES_REQUEST = "RETRIEVE_NOVEDADES_REQUEST";
export const RETRIEVE_NOVEDADES_SUCCESS = "RETRIEVE_NOVEDADES_SUCCESS";
export const RETRIEVE_NOVEDADES_FAILURE = "RETRIEVE_NOVEDADES_FAILURE";

export const UPDATE_NOVEDAD_REQUEST = "UPDATE_EMPRENDIMIENTO_REQUEST";
export const UPDATE_NOVEDAD_SUCCESS = "UPDATE_EMPRENDIMIENTO_SUCCESS";
export const UPDATE_NOVEDAD_FAILURE = "UPDATE_EMPRENDIMIENTO_FAILURE";

export const DELETE_NOVEDAD_REQUEST = "DELETE_EMPRENDIMIENTO_REQUEST";
export const DELETE_NOVEDAD_SUCCESS = "DELETE_EMPRENDIMIENTO_SUCCESS";
export const DELETE_NOVEDAD_FAILURE = "DELETE_EMPRENDIMIENTO_FAILURE";

export const GET_NOVEDAD_BY_ID_REQUEST = "GET_EMPRENDIMIENTO_BY_ID_REQUEST";
export const GET_NOVEDAD_BY_ID_SUCCESS = "GET_EMPRENDIMIENTO_BY_ID_SUCCESS";
export const GET_NOVEDAD_BY_ID_FAILURE = "GET_EMPRENDIMIENTO_BY_ID_FAILURE";

export const DELETE_ALL_NOVEDADES = "DELETE_ALL_EMPRENDIMIENTOS";