
export const RETRIEVE_REPORTE_REQUEST = "RETRIEVE_REPORTE_REQUEST";
export const RETRIEVE_REPORTE_SUCCESS = "RETRIEVE_REPORTE_SUCCESS";
export const RETRIEVE_REPORTE_FAILURE = "RETRIEVE_REPORTE_FAILURE";