
export const RETRIEVE_REPORTE_REQUEST = "RETRIEVE_REPORTE_REQUEST";
export const RETRIEVE_REPORTE_SUCCESS = "RETRIEVE_REPORTE_SUCCESS";
export const RETRIEVE_REPORTE_FAILURE = "RETRIEVE_REPORTE_FAILURE";


export const RETRIEVE_REPORTEGENERO_REQUEST = "RETRIEVE_REPORTEGENERO_REQUEST";
export const RETRIEVE_REPORTEGENERO_SUCCESS = "RETRIEVE_REPORTEGENERO_SUCCESS";
export const RETRIEVE_REPORTEGENERO_FAILURE = "RETRIEVE_REPORTEGENERO_FAILURE";


export const RETRIEVE_REPORTEPROGRAMA_REQUEST = "RETRIEVE_REPORTEPROGRAMA_REQUEST";
export const RETRIEVE_REPORTEPROGRAMA_SUCCESS = "RETRIEVE_REPORTEPROGRAMA_SUCCESS";
export const RETRIEVE_REPORTEPROGRAMA_FAILURE = "RETRIEVE_REPORTEPROGRAMA_FAILURE";