export const CREATE_USER_REQUEST = "CREATE_EMPRENDIMIENTO_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_EMPRENDIMIENTO_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_EMPRENDIMIENTO_FAILURE";

export const LOGIN_USER_REQUEST = "CREATE_EMPRENDIMIENTO_REQUEST";
export const LOGIN_USER_SUCCESS = "CREATE_EMPRENDIMIENTO_SUCCESS";
export const LOGIN_USER_FAILURE = "CREATE_EMPRENDIMIENTO_FAILURE";

export const RETRIEVE_USER_REQUEST = "RETRIEVE_EMPRENDIMIENTOS_REQUEST";
export const RETRIEVE_USER_SUCCESS = "RETRIEVE_EMPRENDIMIENTOS_SUCCESS";
export const RETRIEVE_USER_FAILURE = "RETRIEVE_EMPRENDIMIENTOS_FAILURE";

export const LOGOUT= "LOGOUT";

export const UPDATE_USER_REQUEST = "UPDATE_EMPRENDIMIENTO_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_EMPRENDIMIENTO_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_EMPRENDIMIENTO_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_EMPRENDIMIENTO_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_EMPRENDIMIENTO_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_EMPRENDIMIENTO_FAILURE";

export const GET_USER_BY_ID_REQUEST = "GET_EMPRENDIMIENTO_BY_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_EMPRENDIMIENTO_BY_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_EMPRENDIMIENTO_BY_ID_FAILURE";

export const DELETE_ALL_USERS = "DELETE_ALL_EMPRENDIMIENTOS";