export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILURE = "CREATE_USER_FAILURE";

export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";

export const RETRIEVE_USER_REQUEST = "RETRIEVE_USER_REQUEST";
export const RETRIEVE_USER_SUCCESS = "RETRIEVE_USER_SUCCESS";
export const RETRIEVE_USER_FAILURE = "RETRIEVE_USER_FAILURE";

export const RETRIEVE_USER_BY_ID_REQUEST = "RETRIEVE_USER_BY_ID_REQUEST";
export const RETRIEVE_USER_BY_ID_SUCCESS = "RETRIEVE_USER_BY_ID_SUCCESS";
export const RETRIEVE_USER_BY_ID_FAILURE = "RETRIEVE_USER_BY_ID_FAILURE";

export const LOGOUT= "LOGOUT";

export const RETRIEVE_ALL_USERS_REQUEST = "RETRIEVE_ALL_USERS_REQUEST";
export const RETRIEVE_ALL_USERS_SUCCESS = "RETRIEVE_ALL_USERS_SUCCESS";
export const RETRIEVE_ALL_USERS_FAILURE = "RETRIEVE_ALL_USERS_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const GET_USER_BY_ID_REQUEST = "GET_USER_ID_REQUEST";
export const GET_USER_BY_ID_SUCCESS = "GET_USER_ID_SUCCESS";
export const GET_USER_BY_ID_FAILURE = "GET_USER_ID_FAILURE";

export const DELETE_ALL_USERS = "DELETE_ALL_USERS";